# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-json
-   repo: https://github.com/pycqa/isort
    rev: 5.9.2
    hooks:
    -   id: isort
        types: [python]
        args: ["--profile", "black"]
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.23.0
    hooks:
    -   id: pyupgrade
        types: [python]
-   repo: https://github.com/psf/black
    rev: 21.7b0
    hooks:
    -   id: black
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
    -   id: mypy
        additional_dependencies: [pydantic, types-requests]
-   repo: https://github.com/sondrelg/pep585-upgrade
    rev: "ab1595ee0aa8823dcda1f0bd95b2c194fcd5362b"
    hooks:
    -   id: upgrade-type-hints
