bag_color_palette: dict[str, str] = {
    "Beyond Black": "white",
    "Coffee or Die": "#6B2121",
    "Escape Goat": "#3FEFAC",
    "Flying Elk": "#FFE94A",
    "Gunship": "silver",
    "Liberty": "red",
    "Magia del Campo": "#4ECE4E",
    "Mind, Body & Soul": "#BA2121",
    "Power Llama": "#3749A2",
    "Silencer Smooth": "#B8CCF2",
    "Space Bear": "#DE9153",
    "Tactisquatch": "#D8553A",
    "Blackbeard's Delight": "#7F2E28",
}
